<a href="https://colab.research.google.com/github/j019/Practical-Machine-Learning/blob/main/Day7/CaseStudy_Early_Wakeup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Case Study : Early Wakeup Health
- Dataset : https://www.kaggle.com/datasets/nalisha/early-wakeup-health-and-lifestyle-dataset

In [55]:
import pandas as pd
df = pd.read_csv('/content/early_wakeup_health_dataset.csv')

In [56]:
df.shape

(10000, 64)

In [57]:
df.isna().sum().sum()

np.int64(4662)

In [58]:
df.isna().sum()

Person_ID              0
Age                    0
Gender                 0
Height_cm              0
Weight_kg              0
                      ..
Health_Score           0
Fitness_Level          0
Healthy_Aging_Score    0
Wellness_Category      0
Early_Waker            0
Length: 64, dtype: int64

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB

## drop columns --> personId, height, Weight, Gym_Member,Earlywaker



### Drop Target Columns -->
 - Obesity_risk, Hypertension, sleepdisorder, Cardiovascular,
 - HealthyAgeing, Wellness, Depression_risk_score, Depression_risk

### Target Columns-->
- Fitness_level --> Multi Class Classification task

- Country --> check distribution --> remove less occurence --> Done --> No need to remove

### -->
* Productivity_Score --> to be discussed

In [60]:
df['Country'].value_counts()

Country
USA            1468
India          1206
UK              798
Canada          763
Japan           667
Germany         623
Pakistan        598
Australia       574
Brazil          572
Mexico          491
France          478
Nigeria         470
South Korea     468
Spain           427
Italy           397
Name: count, dtype: int64

In [61]:
# Drop Columns(irrelevant & target Columns)
df.drop(columns=['Obesity_Risk',
'Hypertension_Risk',
'Diabetes_Risk',
'Cardiovascular_Risk',
'Sleep_Disorder_Risk',
'Health_Score',
'Healthy_Aging_Score',
'Wellness_Category',
'Early_Waker',
'Depression_Risk_Score',
'Gym_Member',
'Height_cm',
'Weight_kg',
'Person_ID'],inplace=True)

In [62]:
df.shape

(10000, 50)

## Convert Date Time to Category (Wake Up Time & Sleep Time)
### Preprocessing on Wake up Time & Sleep Time
#### Wake up Time --> Convert to categorical
- 4am - 6am --> Early Morning --> 0
- 6am - 8am --> Morning Time --> 1
- 8am - 10am --> Late --> 2
- 10am - 11am --> Very Late -->3

### Sleep Time --> Convert to categorical
- 6pm - 8pm --> Outlier --> 5
- 8pm - 10pm --> Early --> 0
- 10pm - 12am --> On-time --> 1
- 0am - 3am --> Late --> 2
- 3am - 7am --> Very Late --> 4

In [63]:
df['Wake_Up_Time'] = pd.to_datetime(df['Wake_Up_Time'])
df['Sleep_Time'] = pd.to_datetime(df['Sleep_Time'])

/tmp/ipykernel_1848/214474565.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Wake_Up_Time'] = pd.to_datetime(df['Wake_Up_Time'])
/tmp/ipykernel_1848/214474565.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Sleep_Time'] = pd.to_datetime(df['Sleep_Time'])

In [64]:
df['Wake_Up_Time'].head()

0   2026-06-27 08:59:00
1   2026-06-27 06:35:00
2   2026-06-27 07:31:00
3   2026-06-27 08:36:00
4   2026-06-27 07:07:00
Name: Wake_Up_Time, dtype: datetime64[ns]

In [65]:
df['WT_cat'] = 0 #WakeUp_time -->categorical

In [66]:
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 04:00:00") & (df['Wake_Up_Time'] < "2026-06-27 06:00:00"), "WT_cat" ] = 0
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 06:00:00") & (df['Wake_Up_Time'] < "2026-06-27 08:00:00"), "WT_cat" ] = 1
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 08:00:00") & (df['Wake_Up_Time'] < "2026-06-27 10:00:00"), "WT_cat" ] = 2
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 10:00:00") & (df['Wake_Up_Time'] <= "2026-06-27 11:00:00"), "WT_cat" ] = 3

In [67]:
df['WT_cat'].unique()

array([2, 1, 0, 3])

In [68]:
df['Sleep_Time'].head()

0   2026-06-27 01:29:00
1   2026-06-27 02:25:00
2   2026-06-27 02:24:00
3   2026-06-27 01:19:00
4   2026-06-27 01:20:00
Name: Sleep_Time, dtype: datetime64[ns]

In [69]:
df['Sleep_Time'].sort_values()

7302   2026-06-27 00:00:00
9058   2026-06-27 00:00:00
7792   2026-06-27 00:00:00
7692   2026-06-27 00:00:00
5933   2026-06-27 00:00:00
               ...
7273   2026-06-27 23:59:00
5927   2026-06-27 23:59:00
7115   2026-06-27 23:59:00
2006   2026-06-27 23:59:00
2807   2026-06-27 23:59:00
Name: Sleep_Time, Length: 10000, dtype: datetime64[ns]

In [70]:
df['ST_cat'] = 0

In [71]:
df.loc[(df['Sleep_Time'] >= "2026-06-27 20:00:00") & (df['Sleep_Time'] < "2026-06-27 22:00:00"), "ST_cat" ] = 0
df.loc[(df['Sleep_Time'] >= "2026-06-27 22:00:00") & (df['Sleep_Time'] <= "2026-06-27 23:59:00"), "ST_cat" ] = 1
df.loc[(df['Sleep_Time'] >= "2026-06-27 00:00:00") & (df['Sleep_Time'] < "2026-06-27 03:00:00"), "ST_cat" ] = 2
df.loc[(df['Sleep_Time'] >= "2026-06-27 03:00:00") & (df['Sleep_Time'] < "2026-06-27 07:00:00"), "ST_cat" ] = 3
## Outlier
df.loc[(df['Sleep_Time'] >= "2026-06-27 18:00:00") & (df['Sleep_Time'] < "2026-06-27 20:00:00"), "ST_cat" ] = 4

In [72]:
df['ST_cat'].unique()

array([2, 1, 0, 4, 3])

In [73]:
df.drop(columns=['Wake_Up_Time', 'Sleep_Time'],inplace=True)

In [74]:
df.shape

(10000, 50)

In [75]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Country', 'Occupation', 'Marital_Status',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Daily_Calorie_Intake', 'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Meditation_Practice',
       'Resting_Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
       'Cholesterol_Level', 'Blood_Sugar_Level', 'Energy_Level_Score',
       'Fatigue_Level_Score', 'Immune_Health_Score', 'Mood_Score',
       'Anxiety_Score', 'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Fitness_Level', 'WT_cat', 'ST_cat'],
      dtype='object')

## Fill missing Values

In [77]:
df.isnull().sum() #Exercise_Type,Workout_Intensity,Alcohol_Consumption

Age                                  0
Gender                               0
BMI                                  0
Country                              0
Occupation                           0
Marital_Status                       0
Sleep_Duration_Hours                 0
Sleep_Quality_Score                  0
Number_of_Night_Awakenings           0
Weekend_Sleep_Difference_Hours       0
Nap_Frequency_Per_Week               0
Screen_Time_Before_Bed_Hours         0
Exercise_Frequency_Per_Week          0
Exercise_Duration_Minutes            0
Exercise_Type                      824
Daily_Steps                          0
Morning_Workout                      0
Workout_Intensity                  824
Daily_Calorie_Intake                 0
Water_Intake_Liters                  0
Fruit_Intake_Per_Day                 0
Vegetable_Intake_Per_Day             0
Protein_Intake_Grams                 0
Sugary_Drinks_Per_Week               0
Fast_Food_Meals_Per_Week             0
Breakfast_Regularity_Score           0
Smoking_Status                       0
Alcohol_Consumption               3014
Stress_Level                         0
Working_Hours_Per_Day                0
Sitting_Hours_Per_Day                0
Outdoor_Time_Hours                   0
Social_Interaction_Score             0
Meditation_Practice                  0
Resting_Heart_Rate                   0
Systolic_BP                          0
Diastolic_BP                         0
Cholesterol_Level                    0
Blood_Sugar_Level                    0
Energy_Level_Score                   0
Fatigue_Level_Score                  0
Immune_Health_Score                  0
Mood_Score                           0
Anxiety_Score                        0
Productivity_Score                   0
Focus_Concentration_Score            0
Life_Satisfaction_Score              0
Fitness_Level                        0
WT_cat                               0
ST_cat                               0
dtype: int64

## According to Statisticians ,When we replace it with central tendency then the data is balanced

- Be careful while replacing with mode use .iloc[0] --> in case of multiple modal

In [78]:
df.loc[df['Alcohol_Consumption'].isna() == True, 'Alcohol_Consumption'] = 0

In [79]:
df[['Exercise_Type','Workout_Intensity']].mode().iloc[0]

Exercise_Type        Weight Training
Workout_Intensity           Moderate
Name: 0, dtype: object

In [80]:
#fill_values = df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].mode().iloc[0]
#df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].fillna(fill_values,inplace=True)

In [81]:
fill_values = df.mode().iloc[0]
df.fillna(fill_values,inplace=True)

In [82]:
df.isnull().sum().sum()

np.int64(0)

## Handle Ordinal columns (label_encoding):
- Workout_Intensity
- Smoking_Status
- Alcohol_Consumption

In [83]:
df['Workout_Intensity'].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [84]:
df['Smoking_Status'].unique()

array(['Former', 'Current', 'Never'], dtype=object)

In [85]:
df['Alcohol_Consumption'].unique()

array(['Moderate', 0, 'Light', 'Heavy'], dtype=object)

In [94]:
label_map={
    'Workout_Intensity':{
        'Low':0,
        'Moderate':1,
        'High':2
    },
    'Smoking_Status':{
        'Former':1, 'Current':2, 'Never':0
    },
    'Alcohol_Consumption':{
        'Light':1,
        'Moderate':2,
        'Heavy':3
    }
}

In [95]:
df.replace(label_map,inplace=True)

/tmp/ipykernel_1848/1715271054.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(label_map,inplace=True)

In [96]:
df[df.columns[df.nunique() > 15]].dtypes

Age                                 int64
BMI                               float64
Sleep_Duration_Hours              float64
Sleep_Quality_Score               float64
Weekend_Sleep_Difference_Hours    float64
Screen_Time_Before_Bed_Hours      float64
Exercise_Duration_Minutes           int64
Daily_Steps                         int64
Daily_Calorie_Intake                int64
Water_Intake_Liters               float64
Protein_Intake_Grams              float64
Breakfast_Regularity_Score        float64
Stress_Level                      float64
Working_Hours_Per_Day             float64
Sitting_Hours_Per_Day             float64
Outdoor_Time_Hours                float64
Social_Interaction_Score          float64
Resting_Heart_Rate                  int64
Systolic_BP                         int64
Diastolic_BP                        int64
Cholesterol_Level                 float64
Blood_Sugar_Level                 float64
Energy_Level_Score                float64
Fatigue_Level_Score               float64
Immune_Health_Score               float64
Mood_Score                        float64
Anxiety_Score                     float64
Productivity_Score                float64
Focus_Concentration_Score         float64
Life_Satisfaction_Score           float64
dtype: object

In [97]:
df['Workout_Intensity'].unique()

array([0, 1, 2])

In [98]:
df['Alcohol_Consumption'].unique()

array([2, 0, 1, 3])

In [99]:
df['Smoking_Status'].unique()

array([1, 2, 0])

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             10000 non-null  int64
 1   Gender                          10000 non-null  object
 2   BMI                             10000 non-null  float64
 3   Country                         10000 non-null  object
 4   Occupation                      10000 non-null  object
 5   Marital_Status                  10000 non-null  object
 6   Sleep_Duration_Hours            10000 non-null  float64
 7   Sleep_Quality_Score             10000 non-null  float64
 8   Number_of_Night_Awakenings      10000 non-null  int64
 9   Weekend_Sleep_Difference_Hours  10000 non-null  float64
 10  Nap_Frequency_Per_Week          10000 non-null  int64
 11  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 12  Exercise_Frequency_Per_Week     10000 non-null  int64
 13  Exercise_Duration_Minutes       10000 non-null  int64
 14  Exercise_Type                   10000 non-null  object
 15  Daily_Steps                     10000 non-null  int64
 16  Morning_Workout                 10000 non-null  object
 17  Workout_Intensity               10000 non-null  int64
 18  Daily_Calorie_Intake            10000 non-null  int64
 19  Water_Intake_Liters             10000 non-null  float64
 20  Fruit_Intake_Per_Day            10000 non-null  int64
 21  Vegetable_Intake_Per_Day        10000 non-null  int64
 22  Protein_Intake_Grams            10000 non-null  float64
 23  Sugary_Drinks_Per_Week          10000 non-null  int64
 24  Fast_Food_Meals_Per_Week        10000 non-null  int64
 25  Breakfast_Regularity_Score      10000 non-null  float64
 26  Smoking_Status                  10000 non-null  int64
 27  Alcohol_Consumption             10000 non-null  int64
 28  Stress_Level                    10000 non-null  float64
 29  Working_Hours_Per_Day           10000 non-null  float64
 30  Sitting_Hours_Per_Day           10000 non-null  float64
 31  Outdoor_Time_Hours              10000 non-null  float64
 32  Social_Interaction_Score        10000 non-null  float64
 33  Meditation_Practice             10000 non-null  object
 34  Resting_Heart_Rate              10000 non-null  int64
 35  Systolic_BP                     10000 non-null  int64
 36  Diastolic_BP                    10000 non-null  int64
 37  Cholesterol_Level               10000 non-null  float64
 38  Blood_Sugar_Level               10000 non-null  float64
 39  Energy_Level_Score              10000 non-null  float64
 40  Fatigue_Level_Score             10000 non-null  float64
 41  Immune_Health_Score             10000 non-null  float64
 42  Mood_Score                      10000 non-null  float64
 43  Anxiety_Score                   10000 non-null  float64
 44  Productivity_Score              10000 non-null  float64
 45  Focus_Concentration_Score       10000 non-null  float64
 46  Life_Satisfaction_Score         10000 non-null  float64
 47  Fitness_Level                   10000 non-null  object
 48  WT_cat                          10000 non-null  int64
 49  ST_cat                          10000 non-null  int64
dtypes: float64(23), int64(19), object(8)
memory usage: 3.8+ MB

# X & Y Split

- target : fitness level

In [101]:
X = df.drop(columns=['Fitness_Level'])
Y = df['Fitness_Level']

X.shape, Y.shape

((10000, 49), (10000,))

In [102]:
Y.unique()

array(['Excellent', 'Good', 'Average', 'Poor'], dtype=object)

In [103]:
label_map = {'Excellent':3, 'Good':2, 'Average':1, 'Poor':0}
Y.replace(label_map,inplace=True)

/tmp/ipykernel_1848/1394058508.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y.replace(label_map,inplace=True)

In [104]:
Y.unique()

array([3, 2, 1, 0])

In [105]:
X_ohe = pd.get_dummies(X)
X_ohe.shape

(10000, 91)

In [106]:
X_ohe.columns

Index(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Daily_Steps', 'Workout_Intensity', 'Daily_Calorie_Intake',
       'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Productivity_Score',
       'Focus_Concentration_Score', 'Life_Satisfaction_Score', 'WT_cat',
       'ST_cat', 'Gender_Female', 'Gender_Male', 'Gender_Non-binary',
       'Country_Australia', 'Country_Brazil', 'Country_Canada',
       'Country_France', 'Country_Germany', 'Country_India', 'Country_Italy',
       'Country_Japan', 'Country_Mexico', 'Country_Nigeria',
       'Country_Pakistan', 'Country_South Korea', 'Country_Spain',
       'Country_UK', 'Country_USA', 'Occupation_Accountant',
       'Occupation_Artist', 'Occupation_Athlete', 'Occupation_Chef',
       'Occupation_Doctor', 'Occupation_Entrepreneur', 'Occupation_Freelancer',
       'Occupation_Laborer', 'Occupation_Lawyer', 'Occupation_Manager',
       'Occupation_Nurse', 'Occupation_Retired',
       'Occupation_Software Engineer', 'Occupation_Student',
       'Occupation_Teacher', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Widowed', 'Exercise_Type_Cycling', 'Exercise_Type_HIIT',
       'Exercise_Type_Running', 'Exercise_Type_Sports',
       'Exercise_Type_Swimming', 'Exercise_Type_Walking',
       'Exercise_Type_Weight Training', 'Exercise_Type_Yoga',
       'Morning_Workout_No', 'Morning_Workout_Yes', 'Meditation_Practice_No',
       'Meditation_Practice_Yes'],
      dtype='object')

In [111]:
cat_col = X_ohe.columns[X_ohe.nunique() <= 15]
cat_col.shape

(61,)

In [112]:
cont_col = X_ohe.columns[X_ohe.nunique() > 15]
cont_col.shape

(30,)

## Train-test Split

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_ohe, Y, test_size=0.3, random_state=7,stratify=Y)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((7000, 91), (3000, 91), (7000,), (3000,))

In [115]:
from sklearn.preprocessing import RobustScaler
rc = RobustScaler()
X_train[cont_col] = rc.fit_transform(X_train[cont_col])
X_test[cont_col] = rc.transform(X_test[cont_col])

In [116]:
X_train[cont_col].shape, X_test[cont_col].shape

((7000, 30), (3000, 30))

## Apply Outlier Imputation Using IQR

In [118]:
def outlier_impute_iqr(df,col):
  df1 = df.copy()
  print("Column --> ",col)
  q1,q3 = df1[col].quantile([0.25,0.75])
  iqr = q3-q1
  lb = q1 - 1.5*iqr
  ub = q3 + 1.5*iqr
  df1.loc[(df1[col] < lb),col] = lb
  df1.loc[(df1[col] > ub),col] = ub
  #df1.loc[(df1[col]UB),col] = UB
  print(lb, ub, df1[col].min(), df1[col].max())
  return df1

In [119]:
X_train_io = X_train.copy()
for col in cont_col:
  X_train_io = outlier_impute_iqr(X_train_io,col)

Column -->  Age
-1.9642857142857144 2.0357142857142856 -0.8928571428571429 1.3214285714285714
Column -->  BMI
-2.0089153046062407 1.9910846953937595 -1.4257057949479945 1.9910846953937595
Column -->  Sleep_Duration_Hours
-2.0033557046979866 1.9966442953020134 -2.0033557046979866 1.8523489932885902
Column -->  Sleep_Quality_Score
-2.0 2.0 -2.0 1.7272727272727282
Column -->  Weekend_Sleep_Difference_Hours
-2.0092592592592595 1.9907407407407407 -1.8888888888888888 1.9907407407407407
Column -->  Screen_Time_Before_Bed_Hours
-1.8664122137404582 2.133587786259542 -0.618320610687023 2.133587786259542
Column -->  Exercise_Duration_Minutes
-2.0 2.0 -1.6071428571428572 2.0
Column -->  Daily_Steps
-2.025921583952065 1.9740784160479354 -1.9954409274456169 1.9740784160479354
Column -->  Daily_Calorie_Intake
-1.9973230220107079 2.0026769779892923 -1.9973230220107079 2.0026769779892923
Column -->  Water_Intake_Liters
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column -->  Protein_Intake_Grams
-2.0116959064327484 1.9883040935672516 -1.97953216374269 1.9883040935672516
Column -->  Breakfast_Regularity_Score
-2.0000000000000004 1.9999999999999996 -2.0000000000000004 1.0
Column -->  Stress_Level
-2.0 2.0 -1.2499999999999998 1.9642857142857142
Column -->  Working_Hours_Per_Day
-2.0 2.0 -2.0 2.0
Column -->  Sitting_Hours_Per_Day
-1.9999999999999998 2.0 -1.9999999999999998 2.0
Column -->  Outdoor_Time_Hours
-1.939153439153439 2.060846560846561 -1.3544973544973544 2.060846560846561
Column -->  Social_Interaction_Score
-2.0 2.0 -1.7083333333333333 2.0
Column -->  Resting_Heart_Rate
-2.0 2.0 -2.0 2.0
Column -->  Systolic_BP
-2.0 2.0 -2.0 2.0
Column -->  Diastolic_BP
-2.0 2.0 -2.0 2.0
Column -->  Cholesterol_Level
-1.9952076677316297 2.0047923322683703 -1.9952076677316297 2.0047923322683703
Column -->  Blood_Sugar_Level
-1.9976452119309256 2.0023547880690726 -1.9976452119309256 2.0023547880690726
Column -->  Energy_Level_Score
-2.0 1.9999999999999998 -2.0 1.277777777777778
Column -->  Fatigue_Level_Score
-1.9615384615384617 2.0384615384615383 -0.7307692307692308 2.0384615384615383
Column -->  Immune_Health_Score
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column -->  Mood_Score
-2.0294117647058822 1.9705882352941178 -2.0294117647058822 1.8823529411764715
Column -->  Anxiety_Score
-2.0238095238095237 1.976190476190476 -1.9999999999999996 1.976190476190476
Column -->  Productivity_Score
-1.9666666666666668 2.033333333333333 -1.9666666666666668 2.0
Column -->  Focus_Concentration_Score
-2.0384615384615388 1.9615384615384612 -2.0384615384615388 1.9615384615384612
Column -->  Life_Satisfaction_Score
-1.966666666666667 2.033333333333333 -1.966666666666667 1.733333333333334