<a href="https://colab.research.google.com/github/j019/Practical-Machine-Learning/blob/main/Day5/Basic_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('/content/cleaned_76hd.csv')

In [2]:
df.shape

(282, 39)

In [3]:
df.isna().sum().sum()

np.int64(0)

In [4]:
df.columns

Index(['V3', 'V4', 'V9', 'V10', 'V11', 'V12', 'V14', 'V15', 'V16', 'V18',
       'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28',
       'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V37', 'V38', 'V39',
       'V40', 'V41', 'V43', 'V44', 'V51', 'V55', 'V56', 'V57', 'V58'],
      dtype='object')

# Heart Disease : 0 and 1 ['V58']

In [6]:
df['V58'].unique()

array([0, 1])

In [7]:
X = df.drop(columns=['V58'])
Y = df['V58']
X.shape, Y.shape

((282, 38), (282,))

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=7,stratify=Y)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((197, 38), (85, 38), (197,), (85,))

In [17]:
Y.value_counts(normalize=True)

V58
0    0.546099
1    0.453901
Name: proportion, dtype: float64

In [18]:
Y_train.value_counts(normalize=True)

V58
0    0.548223
1    0.451777
Name: proportion, dtype: float64

In [19]:
Y_test.value_counts(normalize=True)

V58
0    0.541176
1    0.458824
Name: proportion, dtype: float64

## For logistic Regression And SVM(compulsory) we have to do Standardize the data

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [21]:
X_train_sc.shape, X_test_sc.shape

((197, 38), (85, 38))

In [23]:
X_train_sc.mean(), X_test_sc.mean()

(np.float64(-4.0220743291256e-17), np.float64(0.00744590513160098))

In [24]:
X_train_sc.std(), X_test_sc.std()

(np.float64(1.0), np.float64(1.3188528492058205))

## Apply ML Models

In [31]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr = LogisticRegression(class_weight='balanced', random_state=7)
lr.fit(X_train_sc, Y_train)
Y_pred = lr.predict(X_test_sc)

In [30]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81        46
           1       0.78      0.79      0.78        39

    accuracy                           0.80        85
   macro avg       0.80      0.80      0.80        85
weighted avg       0.80      0.80      0.80        85

In [32]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB, BernoulliNB
gnb = GaussianNB()
gnb.fit(X_train_sc, Y_train)
Y_pred = gnb.predict(X_test_sc)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.63      1.00      0.77        46
           1       1.00      0.31      0.47        39

    accuracy                           0.68        85
   macro avg       0.82      0.65      0.62        85
weighted avg       0.80      0.68      0.63        85

In [33]:
# Bernoulli Naive Bayes
bnb = BernoulliNB()
bnb.fit(X_train_sc, Y_train)
Y_pred = bnb.predict(X_test_sc)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        46
           1       0.83      0.74      0.78        39

    accuracy                           0.81        85
   macro avg       0.81      0.81      0.81        85
weighted avg       0.81      0.81      0.81        85

In [40]:
# SVM --> SVC (Support Vector Classifier)
from sklearn.svm import SVC
svc = SVC(class_weight='balanced', random_state=7)
svc.fit(X_train_sc, Y_train)
Y_pred = svc.predict(X_test_sc)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81        46
           1       0.80      0.72      0.76        39

    accuracy                           0.79        85
   macro avg       0.79      0.78      0.78        85
weighted avg       0.79      0.79      0.79        85

In [39]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_sc, Y_train)
Y_pred = knn.predict(X_test_sc)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.78      0.87      0.82        46
           1       0.82      0.72      0.77        39

    accuracy                           0.80        85
   macro avg       0.80      0.79      0.80        85
weighted avg       0.80      0.80      0.80        85

In [38]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='gini',class_weight='balanced',random_state=7)
dtc.fit(X_train_sc, Y_train)
Y_pred = dtc.predict(X_test_sc)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.79      0.72      0.75        46
           1       0.70      0.77      0.73        39

    accuracy                           0.74        85
   macro avg       0.74      0.74      0.74        85
weighted avg       0.75      0.74      0.74        85

In [46]:
def evaluate_model(model, X_train, X_test, Y_train, Y_test):
  model.fit(X_train, Y_train)
  Y_pred = model.predict(X_test)
  print(f"Classification report of {model} : \n{classification_report(Y_test, Y_pred)}")

In [47]:
models = [LogisticRegression(class_weight='balanced', random_state=7),
          GaussianNB(),
          BernoulliNB(),
          SVC(class_weight='balanced', random_state=7),
          DecisionTreeClassifier(criterion='gini',class_weight='balanced',random_state=7),
          KNeighborsClassifier(n_neighbors=5)]
for i in models:
  evaluate_model(i, X_train_sc, X_test_sc, Y_train, Y_test)

Classification report of LogisticRegression(class_weight='balanced', random_state=7) :
              precision    recall  f1-score   support

           0       0.82      0.80      0.81        46
           1       0.78      0.79      0.78        39

    accuracy                           0.80        85
   macro avg       0.80      0.80      0.80        85
weighted avg       0.80      0.80      0.80        85

Classification report of GaussianNB() :
              precision    recall  f1-score   support

           0       0.63      1.00      0.77        46
           1       1.00      0.31      0.47        39

    accuracy                           0.68        85
   macro avg       0.82      0.65      0.62        85
weighted avg       0.80      0.68      0.63        85

Classification report of BernoulliNB() :
              precision    recall  f1-score   support

           0       0.80      0.87      0.83        46
           1       0.83      0.74      0.78        39

    accuracy                           0.81        85
   macro avg       0.81      0.81      0.81        85
weighted avg       0.81      0.81      0.81        85

Classification report of SVC(class_weight='balanced', random_state=7) :
              precision    recall  f1-score   support

           0       0.78      0.85      0.81        46
           1       0.80      0.72      0.76        39

    accuracy                           0.79        85
   macro avg       0.79      0.78      0.78        85
weighted avg       0.79      0.79      0.79        85

Classification report of DecisionTreeClassifier(class_weight='balanced', random_state=7) :
              precision    recall  f1-score   support

           0       0.79      0.72      0.75        46
           1       0.70      0.77      0.73        39

    accuracy                           0.74        85
   macro avg       0.74      0.74      0.74        85
weighted avg       0.75      0.74      0.74        85

Classification report of KNeighborsClassifier() :
              precision    recall  f1-score   support

           0       0.78      0.87      0.82        46
           1       0.82      0.72      0.77        39

    accuracy                           0.80        85
   macro avg       0.80      0.79      0.80        85
weighted avg       0.80      0.80      0.80        85